version: "3.8"

services:
  web:
    build: .
    container_name: auth_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./config/config.php:/var/www/html/config.php
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: auth_db
    restart: always
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: db_username
      PMA_PASSWORD: db_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
